# Samuel COLLADO <scollado@evoliatis.com>
# Replace build line by build if you want to use fresh images
#
# Two directory will be created : web and mysql in the same place
# * web : from laravel application
# * mysql : MySQL database file
# * redis : Redis database file
#
# Enjoy !

# Database
mysql:
  build: images/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_USER: laravel
    MYSQL_PASSWORD: laravel
    MYSQL_DATABASE: laravel
  volumes:
    - ./mysql:/var/lib/mysql
  ports:
    - "3306:3306"

redis:
  build: images/redis
  volumes:
    - ./redis:/data

# PHP Engine
engine:
  build: images/engine
  volumes:
    - ./web:/var/www
  entrypoint:
    - php-fpm
  links:
    - mysql
    - redis

# Web front
front:
  build: images/front
  volumes:
    - ./web:/var/www
  links:
    - engine
  ports:
    - "80:80"
    
# Admin database
phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql
  ports:
    - "8080:80"

